services:
  api:
    build: .
    image: school_route_api:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data:ro
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3